// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALPuxF7FrHbFGfSfk6W52BD7MfrzuEWdI',
    appId: '1:1035195276631:web:ec0dc779433882c4daf212',
    messagingSenderId: '1035195276631',
    projectId: 'foodai-ebd98',
    authDomain: 'foodai-ebd98.firebaseapp.com',
    storageBucket: 'foodai-ebd98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSekBcj3tuYq6M6XAQ18nJ3QhNcRGMHlk',
    appId: '1:1035195276631:android:15b73c5086b9eafddaf212',
    messagingSenderId: '1035195276631',
    projectId: 'foodai-ebd98',
    storageBucket: 'foodai-ebd98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwHAwcztMKkwpJ4zVsNWICyVzZ43tRyQ',
    appId: '1:1035195276631:ios:05911f37e4567ccadaf212',
    messagingSenderId: '1035195276631',
    projectId: 'foodai-ebd98',
    storageBucket: 'foodai-ebd98.firebasestorage.app',
    iosClientId: '1035195276631-f5pdi58pabscar568kf6pvsrcqv54qo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwHAwcztMKkwpJ4zVsNWICyVzZ43tRyQ',
    appId: '1:1035195276631:ios:05911f37e4567ccadaf212',
    messagingSenderId: '1035195276631',
    projectId: 'foodai-ebd98',
    storageBucket: 'foodai-ebd98.firebasestorage.app',
    iosClientId: '1035195276631-f5pdi58pabscar568kf6pvsrcqv54qo7.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALPuxF7FrHbFGfSfk6W52BD7MfrzuEWdI',
    appId: '1:1035195276631:web:451ce0e02052853edaf212',
    messagingSenderId: '1035195276631',
    projectId: 'foodai-ebd98',
    authDomain: 'foodai-ebd98.firebaseapp.com',
    storageBucket: 'foodai-ebd98.firebasestorage.app',
  );
}
